# Makefile
# Autores:

# Samantha Campisi (samanthac07@gmail.com)
# Juan A. Escalante (jaescalante02@gmail.com)

all:
	g++ -O cut.cpp -o cut
	g++ -O change.cpp -o change
	g++ -O change_hash.cpp -o change_hash	
	javac java_timer.java
	
clean:
	rm -rf cut change change_hash
	rm -rf *~ *.class
