#! /bin/bash

# Autores:

# Samantha Campisi (samanthac07@gmail.com)
# Juan A. Escalante (jaescalante02@gmail.com)

# $1 = filename
# $2 = last capture number
# $3 = max length of segment
# $4 = http
# $5 = 
# 

     echo "Welcome 1 times"
     sqlplus / as sysdba @createwet.sql
     cp ../Cap1/$1.* .
     java java_timer time ./WIT $1 $3 >> time_process_WET.txt
     wc -c tmp_WIT/* >> space_WET.txt
     nsegment=`ls tmp_WIT/ | wc -l`
     mv tmp_WIT/ tmp_WET/
     maxseg=`ls -v tmp_WET/*.txt | tail -1 | awk -F. '{print $1}' | awk -F/ '{print $2}'` 
     ./insert_script -f 1 $nsegment $4 WET $1 $[$maxseg+1] tmp_insert.sql
     cp -r tmp_WET/ ../Warcs/
     cp $1.cdx ../Warcs/tmp_WET/
     java java_timer sqlplus / as sysdba @tmp_insert.sql >> time_insert_WET.txt
     rm -r tmp_WET/ ../Warcs/tmp_WET/
     cp $1.warc tmp_old.warc
     cp $1.cdx tmp_old.cdx
     rm $1.* tmp_insert.sql

  
  for (( capture=2; capture<=$2; capture++ ))
  do
     echo "Welcome $capture times"
     sqlplus / as sysdba @createwet.sql
     cp ../Cap$capture/new/$1.* .
     cp $1.cdx tmp_medium.cdx 
     #./last_cdx $1
     java java_timer ./WET tmp_old $1 $3 >> time_process_WET.txt
     wc -c tmp_WET/* >> space_WET.txt
     nsegment=`ls tmp_WET/ | wc -l`
     maxseg=`ls -v tmp_WET/*.txt | tail -1 | awk -F. '{print $1}' | awk -F/ '{print $2}'` 
     ./insert_script -f $capture $[nsegment-2] $4 WET $1  $[$maxseg+1] tmp_insert.sql
     cp -r tmp_WET/ ../Warcs/
     #cp $1.cdx ../Warcs/tmp_WET/
     java java_timer sqlplus / as sysdba @tmp_insert.sql >> time_insert_WET.txt
     rm -r tmp_WET/ ../Warcs/tmp_WET/
     cp $1.warc tmp_old.warc
     mv tmp_medium.cdx tmp_old.cdx
     rm $1.* tmp_insert.sql
  done

  sqlplus / as sysdba @createwet.sql
  rm -f tmp_old.* tmp_medium.cdx

