#! /bin/bash

# Autores:

# Samantha Campisi (samanthac07@gmail.com)
# Juan A. Escalante (jaescalante02@gmail.com)

# $1 = filename
# $2 = last capture number
# $3 = max length of segment
# $4 = http
# $5 = 
# 

     echo "Welcome 1 times"
     cp ../Cap1/$1.* .
     sqlplus / as sysdba @createwar.sql
     java java_timer ./WIT $1 $3 >> time_process_WAR.txt
     wc -c tmp_WIT/* >> space_WAR.txt
     nsegment=`ls tmp_WIT/ | wc -l`
     mv tmp_WIT/ tmp_WAR/
     maxseg=`ls -v tmp_WAR/*.txt | tail -1 | awk -F. '{print $1}' | awk -F/ '{print $2}'`
     #echo "MSG $maxseg"
     ./insert_script -f 1 $nsegment $4 WAR $1 $[$maxseg+1] tmp_insert.sql
     cp -r tmp_WAR/ ../Warcs/
     cp $1.cdx ../Warcs/tmp_WAR/
     java java_timer sqlplus / as sysdba @tmp_insert.sql >> time_insert_WAR.txt
     #sqlplus / as sysdba @createwar.sql
     rm -r tmp_WAR/ ../Warcs/tmp_WAR/
     rm $1.* tmp_insert.sql

  
  for (( capture=2; capture<=$2; capture++ ))
  do
     echo "Welcome $capture times"
     sqlplus / as sysdba @createwar.sql     
     cp ../Cap$capture/$1.* .
     java java_timer ./WAR $1 $3 >> time_process_WAR.txt
     wc -c tmp_WAR/* >> space_WAR.txt
     nsegment=`ls tmp_WAR/ | wc -l`
     maxseg=`ls -v tmp_WAR/*.txt | tail -1 | awk -F. '{print $1}' | awk -F/ '{print $2}'` 
     ./insert_script -f $capture $nsegment $4 WAR $1  $[$maxseg+1] tmp_insert.sql
     cp -r tmp_WAR/ ../Warcs/
     cp $1.cdx ../Warcs/tmp_WAR/
     java java_timer sqlplus / as sysdba @tmp_insert.sql >> time_insert_WAR.txt
     #sqlplus / as sysdba @createwar.sql
     rm -r tmp_WAR/ ../Warcs/tmp_WAR/
     rm $1.* tmp_insert.sql
  done

  sqlplus / as sysdba @createwar.sql

