#! /bin/bash
# Autores:

# Samantha Campisi (samanthac07@gmail.com)
# Juan A. Escalante (jaescalante02@gmail.com)

# $1 = filename
# $2 = last capture number
# $3 = max length of segment
# $4 = http
# $5 = 
# 

     echo "Welcome 1 times"
     sqlplus / as sysdba @createwur.sql
     cp ../Cap1/$1.* .
     java java_timer ./WIT $1 $3 >> time_process_WUR.txt
     wc -c tmp_WIT/* >> space_WUR.txt
     nsegment=`ls tmp_WIT/ | wc -l`
     mv tmp_WIT/ tmp_WUR/
     maxseg=`ls -v tmp_WUR/*.txt | tail -1 | awk -F. '{print $1}' | awk -F/ '{print $2}'` 
     ./insert_script -f 1 $nsegment $4 WUR $1 $[$maxseg+1] tmp_insert.sql
     cp -r tmp_WUR/ ../Warcs/
     cp $1.cdx ../Warcs/tmp_WUR/
     java java_timer sqlplus / as sysdba @tmp_insert.sql >> time_insert_WUR.txt
     rm -r tmp_WUR/ ../Warcs/tmp_WUR/
     cp $1.warc tmp_old.warc
     cp $1.cdx tmp_old.cdx
     rm $1.* tmp_insert.sql

  
  for (( capture=2; capture<=$2; capture++ ))
  do
     echo "Welcome $capture times"
     sqlplus / as sysdba @createwur.sql
     cp ../Cap$capture/$1.* .
     cp $1.cdx tmp_medium.cdx 
     ./last_cdx $1
     java java_timer ./WUR tmp_old $1 $3 >> time_process_WUR.txt
     wc -c tmp_WUR/* >> space_WUR.txt
     nsegment=`ls tmp_WUR/ | wc -l`
     maxseg=`ls -v tmp_WUR/*.txt | tail -1 | awk -F. '{print $1}' | awk -F/ '{print $2}'` 
 # echo "MXSEG $maxseg"
 # ls tmp_WUR
     ./insert_script -f $capture $[nsegment-2] $4 WUR $1  $[$maxseg+1] tmp_insert.sql
     cp -r tmp_WUR/ ../Warcs/
     #cp $1.cdx ../Warcs/tmp_WUR/
     java java_timer sqlplus / as sysdba @tmp_insert.sql >> time_insert_WUR.txt
     rm -r tmp_WUR/ ../Warcs/tmp_WUR/
     cp $1.warc tmp_old.warc
     mv tmp_medium.cdx tmp_old.cdx
     rm $1.* tmp_insert.sql
     #falta new.cdx que esta en tmp_WUR
  done

  sqlplus / as sysdba @createwur.sql
  rm -f tmp_old.* tmp_medium.cdx

