-- createwar.sql
--
-- Archivo de creacion de las tablas necesarias para la tecnica WAR.
--
-- Autores:
--
-- Samantha Campisi (samanthac07@gmail.com)
-- Juan A. Escalante (jaescalante02@gmail.com)

  DROP TABLE WAR_SEGMENTO;
  DROP TABLE WAR_CAPTURA;
  DROP TABLE WAR_PAGINA;

  CREATE TABLE WAR_PAGINA (
       P_ID  NUMBER(8) NOT NULL,  
       P_URL    VARCHAR(512) NOT NULL,
       CONSTRAINT PK_WAR_PAGINA PRIMARY KEY (P_ID)
  ) TABLESPACE TS_WAR;

  CREATE TABLE WAR_CAPTURA (
       C_ID  NUMBER(8) NOT NULL,       
       C_CAPTURA   NUMBER (16) NOT NULL,
       C_FECHA DATE,
       C_CDX BLOB default empty_blob(),
       CONSTRAINT PK_WAR_CAPTURA PRIMARY KEY (C_ID, C_CAPTURA),
       CONSTRAINT FK_WAR_CAP_PAG FOREIGN KEY (C_ID) REFERENCES WAR_PAGINA
  ) TABLESPACE TS_WAR;   

  CREATE TABLE WAR_SEGMENTO (
       S_ID  NUMBER(8) NOT NULL,
       S_CAPTURA   NUMBER (16) NOT NULL,
       S_SEGID     NUMBER (8) NOT NULL,
       S_SEGMENTO BLOB default empty_blob(),
       CONSTRAINT PK_WAR_SEGMENTO PRIMARY KEY (S_ID, S_CAPTURA, S_SEGID),
       CONSTRAINT FK_WAR_SEG_PAG FOREIGN KEY (S_ID) REFERENCES WAR_PAGINA,       
       CONSTRAINT FK_WAR_SEG_CAP FOREIGN KEY (S_ID, S_CAPTURA) REFERENCES WAR_CAPTURA
  ) TABLESPACE TS_WAR;

  ALTER SESSION SET EVENTS= 'immediate trace name flush_cache';
  EXIT;

