-- Autores:
--
-- Samantha Campisi (samanthac07@gmail.com)
-- Juan A. Escalante (jaescalante02@gmail.com)


DROP TABLESPACE TS_WIT
   INCLUDING CONTENTS AND DATAFILES;

DROP TABLESPACE TS_WET
   INCLUDING CONTENTS AND DATAFILES;

DROP TABLESPACE TS_WOT
   INCLUDING CONTENTS AND DATAFILES;

DROP TABLESPACE TS_WAR
   INCLUDING CONTENTS AND DATAFILES;

DROP TABLESPACE TS_WUR
   INCLUDING CONTENTS AND DATAFILES;
